// frontend/src/app/components/shared/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { FukuroService } from '../../../services/fukuro.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  constructor(public fkr:FukuroService, private router:Router ) {}

  ngOnInit() {
    // this.loadScripts()
  }

  salir(){
    if (confirm('¿Desea cerrar sesión?')) {
      this.fkr.token = "";
      localStorage.clear();
      this.router.navigate(['/sesion/entrar']);
    }else{
      return;
    }
  }

  //   loadScripts() {
  //   const dynamicScripts = [
  //     'assets/libs/jquery/jquery.min.js'
  //   ];
  //   for (let i = 0; i < dynamicScripts.length; i++) {
  //     const node = document.createElement('script');
  //     node.src = dynamicScripts[i];
  //     node.type = 'text/javascript';
  //     node.async = false;
  //     node.charset = 'utf-8';
  //     document.getElementsByTagName('head')[0].appendChild(node);
  //   }
  // }
}

<nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary" *ngIf="fkr.token != ''">
    <a class="navbar-brand" [routerLink]="['/inicio']">
        <img src="assets/img/fukurotexto.png" height="20" alt="Fukuro Logo" />
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item" routerLinkActive="active">
                <a class="nav-link" [routerLink]="['/inicio']">Inicio</a>
            </li>
            <li class="nav-item dropdown" routerLinkActive="active">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Areas
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="nav-link" [routerLink]="['/areas/disponibles']">Disponibles</a>
                    <a class="nav-link" [routerLink]="['/areas/subscritas']">Subscritas</a>
                </div>
            </li>
            <li class="nav-item" routerLinkActive="active">
                <a class="nav-link" [routerLink]="['/mensajes']">Mensajes</a>
            </li>
            <li class="nav-item" routerLinkActive="active">
                <a class="nav-link" [routerLink]="['/usuario']">Perfil</a>
            </li>
            <li class="nav-item" routerLinkActive="active">
                <a class="nav-link" (click)="salir()">Cerrar Sesión</a>
            </li>
        </ul>
    </div>
</nav>

// react-frontend/src/components/Navbar/Navbar.js
import React, { Component } from 'react';
import { BrowserRouter as Router, Route, Link } from "react-router-dom";

class Navbar extends Component {
  render() {
    return (
    <nav className="navbar navbar-expand-lg navbar navbar-dark bg-primary">
        <a className="navbar-brand" href="/">
            <img src="assets/img/fukurotexto.png" height="20" alt="Fukuro Logo" />
        </a>
        <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
        </button>
        <div className="collapse navbar-collapse" id="navbarNavDropdown">
            <ul className="navbar-nav">
                <li className="nav-item">
                    <Link className="nav-link" to="/">Inicio</Link>
                </li>
                <li className="nav-item dropdown">
                    <a className="nav-link dropdown-toggle" href="/#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Areas
                    </a>
                    <div className="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <Link className="nav-link" to="/areas/disponibles">Disponibles</Link>
                        <Link className="nav-link" to="/areas/subscritas">Subscritas</Link>
                    </div>
                </li>
                <li className="nav-item">
                    <Link className="nav-link" to="/mensajes">Mensajes</Link>
                </li>
                <li className="nav-item">
                    <Link className="nav-link" to="/usuario">Perfil</Link>
                </li>
                <li className="nav-item">
                    <Link className="nav-link" to="/sesion/entrar">Cerrar Sesión</Link>
                </li>
            </ul>
        </div>
    </nav>
    );
  }
}

export default Navbar;
